apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-user-password: {{ .Values.mysql.userPassword | b64enc }}
