apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecretFile.name }}
type: Opaque
data:
  mongo-username:   {{ .Values.mongoSecretFile.data.mongoUsername }}

  mongo-password:   {{ .Values.mongoSecretFile.data.mongoPassword }}

  mongo-database:   {{ .Values.mongoSecretFile.data.mongoDatabase }}

# stringData:
#   USER_NM: "kwao"
#   USER_PASSWORD: "kwaopassword"
