apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sqlSecretFile.name }}
type: Opaque
data:
  sql-username:   {{ .Values.sqlSecretFile.data.sqlUsername }}

  sql-password:   {{ .Values.sqlSecretFile.data.sqlPassword }}

  sql-database:   {{ .Values.sqlSecretFile.data.sqlDatabase }}


