apiVersion: v2
name: bg-app-chart
description: A Helm chart for deploying the bgApp web application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: demo-dbSQL
    version: 1.0.2
    repository: "https://github.com/RJ-0605/rodney-syself-devops.git"
