# Default values for bg-app-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


app:
  name: demo-crm-app
  spec:
    replicas: 2
  imageBlue: "gcr.io/my-first-kuba/nextjs-docker:3.0"
  namespace: default


config:
  logLevel: "info"
  persistence: "true"




nginx-ingress-controller:
  fullnameOverride: nginx-ingress-controller

nginxIngressController:
  enabled: true

cert-manager: 
  enabled: true 
  installCRDs: true
  fullnameOverride: cert-manager

app: 
  name: bg-app
  spec: 
    replicas: 3
  imageBlue:  "us-central1-docker.pkg.dev/dev-prod-space/bg-slim-app-blue/bg-slim-app-blue:1.9"
  imageGreen: "us-central1-docker.pkg.dev/dev-prod-space/bg-slim-app-green/bg-slim-app-green:1.9"




database:
  enabled: true
  host: "mysql-service.default.svc.cluster.local"
  port: "3306"

  
sqlSecretFile: 
  name: sql-secret
  data:
    sqlUsername: c3FsMzY5OTg4MQ==
    sqlPassword: YnFjTVk5WXZyaQ==
    sqlDatabase: c3FsMzY5OTg4MQ==



certIssuerFile:
  issuerName: letsencrypt-production
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jedidiahkwao@gmail.com
    privateKeySecretName: letsencrypt-staging
    ingressClass: nginx


ingressFile:
  name: bg-app-ingress
  host: bg-app.ddns.net





mongoSecretFile: 
  name: mongo-secret
  data:
    mongoUsername: a3dhbw==
    mongoPassword: a3dhb3Bhc3N3b3Jk
    mongoDatabase: cm9kbmV5bW9uZ29EYXRhYmFzZQ==




