
app:
  name: demo-crm-app
  spec:
    replicas: 2
  imageBlue: "gcr.io/my-first-kuba/nextjs-docker:3.0"
  namespace: prod


hpa:
  minReplicas: 2 
  maxReplicas: 10 
  targetCPUUtilizationPercentage: 80 
  targetMemoryUtilizationPercentage: 80 

config:
  logLevel: "info"
  persistence: "true"


nginx-ingress-controller:
  fullnameOverride: nginx-ingress-controller

nginxIngressController:
  enabled: true

cert-manager: 
  enabled: true 
  installCRDs: true
  fullnameOverride: cert-manager




database:
  enabled: true
  host: "mysql-service.default.svc.cluster.local"
  port: "3306"

  
sqlSecretFile: 
  name: sql-secret
  data:
    sqlUsername: c3FsMzY5OTg4MQ==
    sqlPassword: YnFjTVk5WXZyaQ==
    sqlDatabase: c3FsMzY5OTg4MQ==



certIssuerFile:
  issuerName: letsencrypt-production
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jedidiahkwao@gmail.com
    privateKeySecretName: letsencrypt-staging
    ingressClass: nginx


ingressFile:
  name: bg-app-ingress
  host: bg-app.ddns.net










