apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: default 
spec: 
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

