
apiVersion: v1
kind: Service
metadata:
  name: bg-app-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000






