app:
  name: mysql
  image: mysql:5.7



mysql:
  appName: mysql
  ports: 3306
  services:
    headless:
      name: mysql
    read:
      name: mysql-read
      readonlyLabel: "true"     
  rootPassword: my-root-password
  user: my-user
  userPassword: my-user-password
  mysqlAllowEmptyPassword: "false"

xtrabackup:
  image: gcr.io/google-samples/xtrabackup:1.0

configMap:
  serverIdConfig: |
    [mysqld]
    server-id={{ .Values.serverId }}
  primaryConfig: |
    # Primary configuration
  replicaConfig: |
    # Replica configuration

initScript:
  initCommand: |
    set -ex
    [[ $HOSTNAME =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    echo [mysqld] > /mnt/conf.d/server-id.cnf
    echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
    if [[ $ordinal -eq 0 ]]; then
      cp /mnt/config-map/primary.cnf /mnt/conf.d/
    else
      cp /mnt/config-map/replica.cnf /mnt/conf.d/
    fi

cloneScript:
  cloneCommand: |
    set -ex
    [[ -d /var/lib/mysql/mysql ]] && exit 0
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    ordinal=${BASH_REMATCH[1]}
    [[ $ordinal -eq 0 ]] && exit 0
    ncat --recv-only mysql-$(($ordinal-1)).mysql 3307 | xbstream -x -C /var/lib/mysql
    xtrabackup --prepare --target-dir=/var/lib/mysql

xtrabackupScript:
  backupCommand: |
    set -ex
    cd /var/lib/mysql
    if [[ -f xtrabackup_slave_info && "x$(<xtrabackup_slave_info)" != "x" ]]; then
      cat xtrabackup_slave_info | sed -E 's/;$//g' > change_master_to.sql.in
      rm -f xtrabackup_slave_info xtrabackup_binlog_info
    elif [[ -f xtrabackup_binlog_info ]]; then
      [[ `cat xtrabackup_binlog_info` =~ ^(.*?)[[:space:]]+(.*?)$ ]] || exit 1
      rm -f xtrabackup_binlog_info xtrabackup_slave_info
      echo "CHANGE MASTER TO MASTER_LOG_FILE='${BASH_REMATCH[1]}',\
            MASTER_LOG_POS=${BASH_REMATCH[2]}" > change_master_to.sql.in
    fi
    if [[ -f change_master_to.sql.in ]]; then
      echo "Waiting for mysqld to be ready (accepting connections)"
      until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 1; done
      echo "Initializing replication from clone position"
      mysql -h 127.0.0.1 \
            -e "$(<change_master_to.sql.in), \
                    MASTER_HOST='mysql-0.mysql', \
                    MASTER_USER='root', \
                    MASTER_PASSWORD='', \
                    MASTER_CONNECT_RETRY=10; \
                  START SLAVE;" || exit 1
      mv change_master_to.sql.in change_master_to.sql.orig
    fi
    exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
      "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root"


